from pyrogram import filters, Client
from time import sleep
def datadef():
    return {"name":"AnimationMod","help":"Animation Messages","description":"book - animation book"}
@client.on_message(filters.command("book", prefixes="%") & filters.me)
async def book(client, message):
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
    sleep(0.01)
    await message.edit_text("📕")
    sleep(0.01)
    await message.edit_text("📖")
